# • name - "TechTrends - Package with Docker"

name: TechTrends - Package with Docker

# • Trigger on every push to the main branch

on:
  push:
    branches: [ main ]


jobs:

# • Run the action on the ubuntu-latest operating system
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
# • Push the image to DockerHub with the tag techtrends:latest  
      name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
#          file: ./Dockerfile
         file: ./techtrends/Dockerfile
          platforms: linux/amd64
          push: true
          tags: mctsm/techtrends:latest
